### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by Zhu202308** [RicardooYoung/VersatileTeacher#2]
您好，我想问一下最终在测试集上测量结果是怎么得出来的呢，我看官网的提交界面目标检测是3D目标检测

**Comment by RicardooYoung** [comment]
@xing0806 ，你好。

不知道你说的是哪一个数据集。以Cityscapes为例，数据集包含语义分割标签，可以转换为矩形框供检测任务使用。

祝好。

**Comment by Zhu202308** [comment]
> @xing0806 ，你好。
> 
> 不知道你说的是哪一个数据集。以Cityscapes为例，数据集包含语义分割标签，可以转换为矩形框供检测任务使用。
> 
> 祝好。

对于foggy cityscapes数据集，测试集官方没有给真实标签，那测试集测试之后该怎么得到map呢，谢谢

**Comment by RicardooYoung** [comment]
> > @xing0806 ，你好。
> > 不知道你说的是哪一个数据集。以Cityscapes为例，数据集包含语义分割标签，可以转换为矩形框供检测任务使用。
> > 祝好。
> 
> 对于foggy cityscapes数据集，测试集官方没有给真实标签，那测试集测试之后该怎么得到map呢，谢谢

可以在验证集上进行测试。

**Comment by Zhu202308** [comment]
> > > @xing0806 ，你好。
> > > 不知道你说的是哪一个数据集。以Cityscapes为例，数据集包含语义分割标签，可以转换为矩形框供检测任务使用。
> > > 祝好。
> > 
> > 
> > 对于foggy cityscapes数据集，测试集官方没有给真实标签，那测试集测试之后该怎么得到map呢，谢谢
> 
> 可以在验证集上进行测试。

好的，谢谢你
